### ISSUE TITLE
Can't call `and_then` on `Data::Right` when value is nil

### ISSUE THREAD

**Issue by solnic** [pdswan/unsound#3]
``` ruby
Unsound::Control.try { nil }.and_then { |v| v }.or_else { |v| v }
# *** NoMethodError Exception: undefined method `or_else' for nil:NilClass
```

^^ crashes :)

**Comment by solnic** [comment]
@pdswan I updated title/desc to better explain what I'm seeing

**Comment by pdswan** [comment]
Much appreciated, thanks! I'll take a look tonight (EST)

**Comment by pdswan** [comment]
@solnic ah, yeah, I think this case may be a bit unintuitive. 

`Data::Either#and_then` is an alias for `Data::Either#>>` which take a function/block with the signature `a -> Data::Either b`; It's meant to compose multiple computations that may result in an error.

I followed [rust's](https://doc.rust-lang.org/std/result/enum.Result.html) example here, but it may be more natural to alias `#and_then` to `#fmap` instead of `#>>`.

I also considered adding a run-time check to make sure the function/block returns the proper type.

As it stands you have a few options:

``` ruby
Unsound::Control.try { nil }.and_then { |v| Data::Right.new(v) }.or_else { |e| ... }
Unsound::Control.try { nil }.and_then { |v| Data::Either.of(v) }.or_else { |e| ... }
Unsound::Control.try { nil }.fmap { |v| v }.or_else { |e| ... }
Unsound::Control.try { nil }.either(->(e) { e }, ->(v) { v })
```

The [use cases spec](https://github.com/pdswan/unsound/blob/master/spec/integration/try_spec.rb) has more realistic examples that may provide better clarification.

Curious to hear your thoughts.

In either case I think the docs could be improved, but I'm still looking for the best way to express this via yard.

**Comment by solnic** [comment]
@pdswan my use case is that I have a bunch of ops, some may raise some may return nil. Something like this:

``` ruby
try {
  op_1 # may raise
}.fmap { |v|
  v.get_result # may return nil O_o
}.and_then { |v|
  # and here I'm not sure how to approach this as it might be nil
}
```

**Comment by pdswan** [comment]
@solnic thanks for clarifying.

I think there are two ways to think about this:
1. if `nil` is considered an error condition here, we can treat it as such and do something like:
   
   ``` ruby
   try {
     op_1 # may raise
   }.and_then { |v|
     if result = v.get_result
       Unsound::Data::Right.new(result)
     else
       Unsound::Data::Left.new(RuntimeError.new("No Results"))
     end
   }.and_then { |v|
     # won't get here now
   }
   ```
2. If instead we separate the the exceptional error handling from the handling of no results, we can use `Unsound::Data::Maybe`
   
   ``` ruby
   try {
     op_1 # may raise
   }.fmap { |v|
     if result = v.get_result
       Unsound::Data::Just.new(result)
     else
       Unsound::Data::Nothing.new
     end
   }.fmap { |v|
     v.fmap { |result|
       # do something with the result from the previous fmap, will be skipped if it's nothing
     }
   }
   ```
   
   In this case, v.get_result could also be modified to return a `Data::Unsound::Nothing` in the nil case.

I believe the second solution is preferable since it separates the two different concerns; in fact, I think this probably warrants something like `Unsound::Control.try` to support dealing with existing ruby code:

``` ruby
module Unsound
  module Control
    module_function

    def maybe(f = nil, &blk)
      if result = (f || blk).call
        Data::Just.new(result)
      else
        Data::Nothing.new
      end
    end
  end
end

try {
  op_1 # may raise
}.fmap { |v|
  Unsound::Control.maybe { v.get_result }
}.fmap { |v|
  v.fmap { |result|
    # do something with the result from the previous fmap, will be skipped if it's nothing
  }
}
```

It will probably take a little experimentation to make this more elegant, this is something I'm still working through as far a functional programming paradigms are concerned.

Curious to hear your thoughts.

**Comment by solnic** [comment]
Yes I kind of expected there would be something like `maybe` :)

**Comment by pdswan** [comment]
@solnic agreed, then.

will gladly accept a pull request if you're blocked, otherwise i'll implement it tonight!

appreciate all the feedback. cheers!

**Comment by solnic** [comment]
nah I'm not blocked, I just did `if/else` YUCK :)

Would love to send a PR but I don't have enough time.
